services:
  preliminary-actions:
    image: fedora:${FEDORA_VERSION_NUM}
    command: >
      bash -c "
        [[ -d './test/served-tmp/' ]] || mkdir '/test/served-tmp/' && \
        [[ -d './test/diff/' ]] || mkdir '/test/diff/' && \
        [[ -d './test/unit-tmp/' ]] || mkdir '/test/unit-tmp/' && \
        [[ -d './test/e2e/playwright/test-results/' ]] || \
          mkdir './test/e2e/playwright/test-results/' && \
        [[ -d './test/e2e/playwright/playwright-report/' ]] || \
          mkdir './test/e2e/playwright/playwright-report/' && \
        chmod 777 './test/e2e/playwright/test-results/' && \
        chmod 777 './test/e2e/playwright/playwright-report/'"
    volumes:
      - ./test:/test
    restart: "no"

  main:
    depends_on:
      preliminary-actions:
        condition: service_completed_successfully
        restart: false
    image: ${PROJECT_NAME}-main:${MAIN_IMAGE_TAG}
    pull_policy: never
    environment:
      LIVERELOAD_PORT: 35729
      VAR_DIR_CONTAINED: ${VAR_DIR_CONTAINED}
    ports:
      - "8080:443"
      - "35729:35729"
    volumes:
      - ./var:/home/${PROJECT_NAME}/var
      - ./dist:/home/${PROJECT_NAME}/dist
      - ./flow:/home/${PROJECT_NAME}/flow
      - ./test:/home/${PROJECT_NAME}/test

  docs:
    image: ${PROJECT_NAME}-docs:${DOCS_IMAGE_TAG}
    pull_policy: never
    ports:
      - "8081:3000"
    environment:
      VAR_DIR_CONTAINED: ${VAR_DIR_CONTAINED}
      #this should be removed once https://github.com/nodejs/node/issues/60704 is fixed
      NODE_OPTIONS: "--no-experimental-webstorage"
    volumes:
      - ./dist:/home/${PROJECT_NAME}/dist
      - ./docs:/home/${PROJECT_NAME}/docs
      - ./docs-src/blog:/home/${PROJECT_NAME}/docs-src/blog
      - ./docs-src/docs:/home/${PROJECT_NAME}/docs-src/docs
      - ./docs-src/src:/home/${PROJECT_NAME}/docs-src/src
      - ./docs-src/static:/home/${PROJECT_NAME}/docs-src/static
      - ./docs-src/var:/home/${PROJECT_NAME}/docs-src/var

  playwright:
    image: ${PROJECT_NAME}-playwright:${PLAYWRIGHT_IMAGE_TAG}
    pull_policy: never
    user: "1001"
    #to serve the report via a server if there is a need if one cannnot open
    #the index.html file via the file:// schema
    #ports:
    #  - "8082:9323"
    volumes:
      - ./test/e2e/playwright/var:/home/pwuser/var
      - ./test/e2e/playwright/specs:/home/pwuser/specs
      - ./test/e2e/playwright/playwright-report:/home/pwuser/playwright-report:U
      - ./test/e2e/playwright/test-results:/home/pwuser/test-results:U
    command: bash
    tty: true
    stdin_open: true
