// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  docsSidebar: [
    {
      type: 'category',
      label: 'Overview',
      items: [
        'overview/introduction',
        'overview/prerequisites',
        'overview/usage',
        'overview/current-limitations',
        'overview/caveats',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api-ref/x-charts-js',
        {
          type: 'category',
          label: 'Components',
          items: [
            'api-ref/components/legend',
            'api-ref/components/pie-3d',
          ],
        },
      ],
    },
  ],
  sandboxAndRefSidebar: [
    'sandbox-n-ref/intro',
    {
      type: 'category',
      label: 'Tutorial Basics',
      items: [
        'sandbox-n-ref/tutorial-basics/congratulations',
        'sandbox-n-ref/tutorial-basics/create-a-blog-post',
        'sandbox-n-ref/tutorial-basics/create-a-document',
        'sandbox-n-ref/tutorial-basics/create-a-page',
        'sandbox-n-ref/tutorial-basics/deploy-your-site',
        'sandbox-n-ref/tutorial-basics/markdown-features',
      ],
    },
    {
      type: 'category',
      label: 'Tutorial Extras',
      items: [
        'sandbox-n-ref/tutorial-extras/manage-docs-versions',
        'sandbox-n-ref/tutorial-extras/translate-your-site',
      ],
    },
  ],
};

export default sidebars;
